# 2023-10-14 15:20
name: act-build-centos
run-name: far2l 2.5.2 - centos

on:
  workflow_dispatch:
#  repository_dispatch:
#    types: [build-nightly]
env:
   client_payload_tag: '2.5.2'
   client_payload_sha: 'c7d34d0'
   client_payload_repo: 'deep-soft/far2l'
   client_payload_date: '20231014'
   client_payload_url: 'deep-soft/far2l'
   client_payload_message: 'far2l portable'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: centos
            version: '7'
    container: ${{ matrix.distro }}:${{ matrix.version }}
    steps:
      - name: Add build dependencies
        env:
          #ccache cmake file g++ libarchive-dev libneon27-dev libnfs-dev libpcre3-dev libsmbclient-dev libssh-dev
          #libuchardet-dev libxerces-c-dev libxi-dev libtree makeself ninja-build patch patchelf quilt wget
          PACKAGES: >
            ccache cmake file g++ libarchive-devel neon-devel libnfs-devel pcre-devel libsmbclient-devel 
            libssh-devel uchardet-devel libxerces-c-devel libXi-devel libtree makeself ninja-build patch patchelf quilt wget curl
        run: |
          if [ "${{ matrix.distro }}" = "centos" ]; then
            yum update -y 
            yum --enablerepo=extras install -y epel-release
            yum --enablerepo=epel install -y ${{ env.PACKAGES }}
            yum install centos-release-scl
            yum install devtoolset-8-gcc devtoolset-8-gcc-c++
            scl enable devtoolset-8 -- bash
            nvm install 16.15.1
            # echo "deb [trusted=yes] http://ppa.launchpad.net/far2l-team/tools/ubuntu xenial main" | tee /etc/apt/sources.list.d/far2l-team.list
            # apt update -qq && apt install -y --no-install-recommends ${{ env.PACKAGES }}
          fi

      - name: Checkout
        uses: deep-soft/checkout@v4

      - name: Checkout far2l
        uses: deep-soft/checkout@v4
        with:
          repository: ${{ env.client_payload_repo }}
          path: far2l

      - name: Setup ccache
        uses: deep-soft/cache@v3
        with:
          path: ${{ github.workspace }}/.ccache
          key: ccache-${{ matrix.distro }}-${{ matrix.version }}-${{ env.client_payload_sha }}
          restore-keys: |
            ccache-${{ matrix.distro }}-${{ matrix.version }}-

      - name: Build far2l
        working-directory: ./far2l
        env:
          DATE: ${{ env.client_payload_date }}
          SHA:  ${{ env.client_payload_sha }}
          TAG:  ${{ env.client_payload_tag }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          DESTDIR: ${{ github.workspace }}/AppDir
          STANDALONE: true
        shell: bash
        run: |
          export VERSION=${TAG}.git${DATE}
          export PKG_NAME=far2l_${VERSION}_$(uname -m)-glibc
          bash -x ${GITHUB_WORKSPACE}/build_far2l.sh

      - name: Archive Release
        uses: deep-soft/zip-release@v2
        with:
          type: 'zip'
          filename: 'far2l-${{ matrix.distro }}-${{ matrix.version }}.zip'
          directory: 'far2l/build/install'
          # archive name is ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: Upload artifact
        uses: deep-soft/upload-artifact@v3
        with:
          name: far2l-${{ matrix.arch }}
          path: |
            ./**/far2l*.tar*
          if-no-files-found: error

      - name: Publish Release
        continue-on-error: true
        uses: deep-soft/release-action@v1
        with:
          draft: ${{ env.DRAFT }}
          tag: ${{ env.client_payload_name }}-${{ env.client_payload_tag }}
          allowUpdates: true
          artifacts: |
            ./**/far2l*.tar
            ${{ env.ZIP_RELEASE_ARCHIVE }}
